# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - uses: 1arp/create-a-file-action@0.4.5
      with:
        path: 'environments'
        isAbsolutePath: false
        file: 'environment.ts'
        content: |
          export const environment = {
            production: true,
            hostName: 'ec2-3-131-37-201.us-east-2.compute.amazonaws.com',
            SECRET_GPT_API: ${{ secrets.GPT_API }} };
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
